endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        size: 300
        margin: 10
        encoding: UTF-8
        errorCorrectionLevel: 'high'
    validation:
        writer: Endroid\QrCode\Writer\SvgWriter
        size: 150
        margin: 4