security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            custom_authenticators:
                - App\Security\LoginAuthenticator
                - App\Security\FacialRecognitionAuthenticator
            entry_point: App\Security\LoginAuthenticator
            
            # Configure 2FA with explicit routes
            two_factor:
                auth_form_path: app_2fa_login   # Path to the 2FA form
                check_path: 2fa_login_check     # Path that checks the 2FA authentication
                post_only: false                # Allow non-POST requests to check path
                csrf_token_manager: security.csrf.token_manager
                
            logout:
                path: app_logout
                target: /login
                invalidate_session: true
                
    access_control:
        # Allow access to the 2FA process paths for any authenticated user
        - { path: ^/2fa, role: IS_AUTHENTICATED_PARTIALLY }
        - { path: ^/profile/2fa, role: IS_AUTHENTICATED_REMEMBERED }
        
        # Public access to login, signup and similar routes
        - { path: ^/(login|signup|reset-password|verify-email|css|js|images|fonts|favicon), roles: PUBLIC_ACCESS }
        - { path: ^/login/face, roles: PUBLIC_ACCESS }
        - { path: ^/login/face/verify, roles: PUBLIC_ACCESS }
        - { path: ^/login/face/check, roles: PUBLIC_ACCESS }
        - { path: ^/health-check, roles: PUBLIC_ACCESS }
        - { path: ^/api/public, roles: PUBLIC_ACCESS }
        
        # Special access for 2FA check endpoints
        - { path: ^/2fa/check, roles: IS_AUTHENTICATED_PARTIALLY }
        
        # Default route - require authenticated user
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
