security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: auto
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginAuthenticator
                - App\Security\FacialRecognitionAuthenticator
                - App\Security\GoogleOAuthAuthenticator
            logout:
                path: app_logout
                target: /login
                invalidate_session: true
                csrf_parameter: _csrf_token
                csrf_token_id: logout
            form_login:
                login_path: app_login
                check_path: app_login
            entry_point: form_login
            # switch_user: true  # décommenter si tu veux activer l'usurpation d'utilisateur

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/signup, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google/check, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/reclamation, roles: ROLE_ADMIN }
        - { path: ^/driver, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/, roles: [PUBLIC_ACCESS, ROLE_USER] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
