version: '3.8'

services:
  apache:
    image: httpd:2.4
    container_name: wamia_apache
    ports:
      - "8080:80"
    volumes:
      - .:/usr/local/apache2/htdocs/
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: wamia_mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Allows empty root password
      MYSQL_ROOT_PASSWORD: ''            # Explicit empty password
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wamia_phpmyadmin
    restart: always
    environment:
      PMA_HOST: wamia_mysql   # Must match MySQL container_name
      PMA_USER: root
      PMA_PASSWORD: ''        # Empty password to match MySQL
      PMA_ARBITRARY: 1        # Allows empty password login
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge