# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Speech\AzureSpeechService:
        public: true

    App\Service\Export\PdfExportService:
        arguments:
            $twig: '@twig'

    # Configure Dompdf as a service
    Dompdf\Dompdf:
        calls:
            - [setOptions, ['@dompdf.options']]

    dompdf.options:
        class: Dompdf\Options
        calls:
            - [setIsHtml5ParserEnabled, [true]]
            - [setIsRemoteEnabled, [true]]
            - [setIsPhpEnabled, [true]]
            - [setDefaultFont, ['DejaVu Sans']]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Twig\Extension\ImageExtension:
        tags: ['twig.extension']
    
    App\Service\OpenAIService:
        arguments:
            $apiKey: '%env(OPENAI_API_KEY)%'

    App\Service\EmailService:
        arguments:
            $mailer: '@mailer'
            $logger: '@logger'
