# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best-practices.html#use-parameters-for-application-configuration
parameters:
    twilio.account_sid: '%env(TWILIO_ACCOUNT_SID)%'
    twilio.auth_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio.from_number: '%env(TWILIO_FROM_NUMBER)%'
    gemini.api_key: '%env(GEMINI_API_KEY)%'
    app.openweather_api_key: '%env(OPENWEATHER_API_KEY)%'
    app.gemini_api_key: '%env(GEMINI_API_KEY)%'
    azure.tts.region: '%env(AZURE_TTS_REGION)%'
    azure.tts.key: '%env(AZURE_TTS_KEY)%'
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    app.here_api_key: 'DW9egp1lljrp_9klXkmSp8y-SuoywTOGIspZgdGCGlg'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    dompdf.wrapper:
        class: Dompdf\Dompdf
        arguments: [] # Automatically registers your services as commands, event subscribers, etc.


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\AzureTTSService:
        arguments:
            $region: '%azure.tts.region%'
            $key: '%azure.tts.key%'

    App\Service\GeminiService:
        arguments:
            $geminiApiKey: '%gemini_api_key%'

    App\Controller\Admin\taxi\TaxiManagementController:
        arguments:
            $pdf: '@dompdf.wrapper'

            

    # Twilio service configuration
    App\Service\TwilioService:
        arguments:
            $accountSid: '%twilio.account_sid%'
            $authToken: '%twilio.auth_token%'
            $fromNumber: '%twilio.from_number%'

    # Gemini Chat service configuration
    App\Service\GeminiChatService:
        arguments:
            $apiKey: '%gemini.api_key%'

    # Geo-routing service for bicycle module
    App\Service\Geo\GeoRoutingService:
        arguments:
            $logger: '@logger'

    # Configure Gemini API Service with API key
    App\Service\GeminiApiService:
        arguments:
            $httpClient: '@http_client'
            $apiKey: '%gemini.api_key%'

    # Add UserRepository as a global Twig variable
    App\Repository\UserRepository:
        public: true

    # Azure Speech service
    App\Service\Speech\AzureSpeechService:
        public: true

    # PDF export service
    App\Service\Export\PdfExportService:
        arguments:
            $twig: '@twig'

    # Configure Dompdf as a service
    Dompdf\Dompdf:
        calls:
            - [setOptions, ['@dompdf.options']]

    dompdf.options:
        class: Dompdf\Options
        calls:
            - [setIsHtml5ParserEnabled, [true]]
            - [setIsRemoteEnabled, [true]]
            - [setIsPhpEnabled, [true]]
            - [setDefaultFont, ['DejaVu Sans']]

    # Twig extension
    App\Twig\Extension\ImageExtension:
        tags: ['twig.extension']

    # OpenAI service
    App\Service\OpenAIService:
        arguments:
            $apiKey: '%env(OPENAI_API_KEY)%'

    # Email service
    App\Service\EmailService:
        arguments:
            $mailer: '@mailer'
            $logger: '@logger'


    # Explicitly define the TrafficTimeEstimator service
    App\Service\TrafficTimeEstimator:
        arguments:
            $httpClient: '@http_client'
            $apiKey: '%app.here_api_key%'


    App\Service\PredictPrice:
        arguments:
            $logger: '@logger'
    App\Service\DeepSeekService:
        arguments:
            $apiKey: '%env(DEEPS_EEK_API_KEY)%'
            $httpClient: '@http_client'
            $logger: '@logger'

    # Admin access listener to restrict admin users to only dashboard
    App\EventListener\AdminAccessListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', priority: 9 }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
